Tooltip over the various portals on the left
ow2-proactive/automation-dashboard pull request #466
Opened 2021-09-20 09:49 UTC by medou-boushab

2021-09-20 09:51 UTC, mboussaa commented on app/resources/locales/locale-fr.json
> +  "Associate Workflows to Calendar": "Associer les workflows au calendrier",
workflows => Workflows
calendrier => Calendrier

2021-09-20 09:53 UTC, mboussaa requested changes
preserve capital letters in different languages. Thx

2021-09-21 10:14 UTC, carolinepacheco commented on app/resources/locales/locale-pt.json
> +  "Browse and Search the Catalog": "Navegue e pesquise o catálogo",
Navegue e pesquise o catálogo -> Navegar e Pesquisar no catálogo

2021-09-21 10:14 UTC, carolinepacheco commented on app/resources/locales/locale-pt.json
> +  "See Graphical view of Past and Future Executions": "Veja a visão gráfica das execuções passadas e futuras",
Veja a visão gráfica das execuções passadas e futuras -> Veja a visualização gráfica das execuções passadas e futuras

2021-09-23 10:03 UTC, mboussaa commented on app/resources/locales/locale-fr.json
> +  "Browse and Search the Catalog": "Parcourir et rechercher le Catalogue",
Rechercher

2021-09-23 22:05 UTC, merged