Use same submission wizard in other portals
ow2-proactive/automation-dashboard pull request #487
Opened 2022-01-31 13:17 UTC by medou-boushab

2022-02-02 19:06 UTC, tao-xinxiu approved these changes
LGTM

2022-02-07 22:06 UTC, amouhoub requested changes
I gave you a first review.
I'll do another one once you apply the requested changes...
It's pretty big :D

2022-02-07 22:06 UTC, amouhoub commented on app/templates_versions/enterprise/subviews.json
> -            "workflow-execution/templates/typehead-wf-dropdown.html",
same comment as above... 
Don't remove
```
"workflow-execution/templates/typehead-wf-dropdown.html",
```

2022-02-08 08:26 UTC, medou-boushab commented on app/scripts/main.js
> +    const submitServicesAndAction = function () {
We do submit services&actions from WE and Cloud Automation
In this Controller, we put functions that will be called when the user clicks on footer button

2022-02-08 08:27 UTC, medou-boushab commented on app/scripts/main.js
> +    const submit = function () {
same, in Catalog and in WE

2022-02-09 11:05 UTC, medou-boushab commented on app/scripts/utils.js
> +        return JSON.parse(localStorage.WizardUserPreferences)
I tried this but it's too difficult to make them generic because we need to pass two parameters the object and the itemName.

The only solution is to put all preferences in the same object, which is not a good idea

2022-02-10 23:39 UTC, merged