remove show all checkbox for PA:CATALOG var modal
ow2-proactive/automation-dashboard pull request #492
Opened 2022-03-03 11:01 UTC by tao-xinxiu

2022-03-07 14:51 UTC, medou-boushab requested changes

2022-03-07 14:53 UTC, tao-xinxiu commented on app/scripts/modals/catalog-objects-modal-controller.js
> +        var objectName = $('#get-object-by-name input').val();
Updated.

2022-03-07 14:54 UTC, tao-xinxiu commented on app/views/modals/catalog_objects_modal.html
> +        <form class="container-flex w-100" id="get-object-by-name" ng-submit="filterByObjectsByName()">
This id is actually only used in css, not for retrieving any data.

2022-03-08 09:28 UTC, medou-boushab approved these changes

2022-03-11 17:22 UTC, merged