show-error-message-when-server-is-unresponsive
ow2-proactive/automation-dashboard pull request #600
Opened 2023-09-25 08:29 UTC by oanaBiancaSchiopu

![image](https://github.com/ow2-proactive/automation-dashboard/assets/80052076/722cda75-0d40-47ed-acec-cefc37b921b2)

![image](https://github.com/ow2-proactive/automation-dashboard/assets/80052076/78fa4088-e8f9-4cdc-bc5c-643134a5f8bc)

2023-09-25 13:48 UTC, medou-boushab commented on app/scripts/main.js
> +                    var connectionError = $('<div id="connection-error"><label style="color:red; font-weight:bold; font-size:15px; padding-left:30px;">The server cannot be reached. Check first your n
better to use a directive ng-if or ng-show

2023-09-25 13:51 UTC, medou-boushab commented on app/scripts/main.js
> +                    var connectionError = $('<div id="connection-error"><label style="color:red; font-weight:bold; font-size:15px; padding-left:30px;">The server cannot be reached. Check first your n
please use what we have in inspian to be consistent with that used in submission view alerts.

2023-09-26 17:10 UTC, mboussaa approved these changes

2023-09-26 20:48 UTC, amouhoub requested changes
Yes, as @medou-boushab pointed out, angular hates manipulating elements with jQuery.
Use a scope variable for when you get errors and display the message directly in HTML using ng-if

2023-09-27 08:00 UTC, oanaBiancaSchiopu commented
> Yes, as @medou-boushab pointed out, angular hates manipulating elements with jQuery. Use a scope variable for when you get errors and display the message directly in HTML using ng-if

@amouhoub is your comment still up to date? I have commited some changes after the comment of Medou

2023-09-28 09:15 UTC, amouhoub approved these changes

2023-09-28 10:04 UTC, merged