logout-confirmation
ow2-proactive/automation-dashboard pull request #620
Opened 2024-01-23 14:54 UTC by oanaBiancaSchiopu

![image](https://github.com/ow2-proactive/automation-dashboard/assets/80052076/8d028a85-9770-4ad5-8bf9-b5b99de38b7c)

2024-01-24 21:18 UTC, amouhoub requested changes

2024-01-24 21:18 UTC, amouhoub commented on app/views/common/topnavbar.html
> +                        <div style="padding:15px; text-align:center;" ng-controller="logoutController">
Use the class `text-center` instead of applying text-align:enter as an inline style
Use `p-sm` class instead of padding:15px in an inline style

2024-01-24 21:18 UTC, amouhoub commented on app/views/common/topnavbar.html
> +                        <div style="padding:15px;">
Use `p-sm` class instead of padding:15px in an inline style

2024-01-24 21:18 UTC, amouhoub commented on app/views/common/topnavbar.html
> +                            <h4 style="text-align: center">{{'Are you sure you want to exit?'|translate}}</h4>
Use the class `text-center` instead of applying text-align:enter as an inline style

2024-01-24 21:18 UTC, amouhoub commented on app/views/common/topnavbar.html
> +                                    aria-hidden="true" style="margin-left:10px;">
Use `m-l-sm` class instead of margin-left:10px in an inline style

2024-01-25 10:49 UTC, medou-boushab commented on app/views/common/topnavbar.html
> +                    <div class="m-t-lg" style="float:left; padding-left:50px;">
use please the className, pull-left instead of float:left

2024-01-25 10:49 UTC, medou-boushab commented on app/views/common/topnavbar.html
> +                            <button id="cancel-logout-button" class="btn btn-white m-l-sm" data-dismiss="modal"
do you use id="cancel-logout-button" ?

2024-01-25 11:55 UTC, oanaBiancaSchiopu commented on app/views/common/topnavbar.html
> +                            <button id="cancel-logout-button" class="btn btn-white m-l-sm" data-dismiss="modal"
I will remove it

2024-01-25 13:09 UTC, amouhoub commented on app/views/common/topnavbar.html
> +                        <div style="padding:15px;">
@oanaBiancaSchiopu don't forget this

2024-01-25 13:10 UTC, amouhoub commented on app/views/common/topnavbar.html
> +                            <h4 style="text-align: center">{{'Are you sure you want to exit?'|translate}}</h4>
@oanaBiancaSchiopu don't forget this

2024-01-25 13:10 UTC, amouhoub commented on app/views/common/topnavbar.html
> +                                    aria-hidden="true" style="margin-left:10px;">
@oanaBiancaSchiopu don't forget this

2024-01-25 13:33 UTC, oanaBiancaSchiopu commented on app/views/common/topnavbar.html
> +                        <div style="padding:15px;">
I have already changed this

2024-01-25 13:34 UTC, oanaBiancaSchiopu commented on app/views/common/topnavbar.html
> +                            <h4 style="text-align: center">{{'Are you sure you want to exit?'|translate}}</h4>
I have already changed this

2024-01-25 13:41 UTC, amouhoub approved these changes

2024-01-25 14:18 UTC, merged